### ISSUE TITLE
Ok button does not remove message

### ISSUE THREAD

**Issue by JRCrawford** [fairlane/cookie-consent-bundle#1]
It looks like the "ok" button does not remove the message when clicked as seen here: https://i.imgur.com/WIi2X3n.gif

**Comment by ghost** [comment]
Hi @JRCrawford, the message does not disappear on click. However the message bar should be gone after you have clicked ok & refreshed the page. The basic functionality is simple: 
1) when clicking the ok button an ajax call is made and in response the cookie is set
2) in [twig](https://github.com/fairlane/cookie-consent-bundle/blob/master/Resources/views/cookie-info.html.twig#L1)  I show the message bar only when the cookie is not set
