### ISSUE TITLE
Google Analytics Cookie

### ISSUE THREAD

**Issue by velkony** [fairlane/cookie-consent-bundle#2]
Hi, 
how can I use the bunde for Google Analytics Cookie?
When the user does not agree to accept the cookies, the bundle must block the Google Analytics.

**Comment by ghost** [comment]
Hi @velkony, this is something you need to implement yourself. This bundle only provides the basic cookie consent notification. You can access the cookie set by this bundle (https://github.com/fairlane/cookie-consent-bundle/blob/master/Type/Constant.php#L23) in your app and build your own logic to skip Google Analytics if the cookies has not been accepted by the visitor

**Comment by velkony** [comment]
Do you have an example where you used Google Analytics from some of your projects?

**Comment by ghost** [comment]
Not really but you can access the cookie either from twig (https://github.com/fairlane/cookie-consent-bundle/blob/master/Resources/views/cookie-info.html.twig#L1) or from the controller using Request (https://api.symfony.com/3.4/Symfony/Component/HttpFoundation/Request.html) and omit Google Analytics script if cookie is not found. Just a word of warning, if you don't include GA script into the first page load (when visitor hasn't accepted the cookies) you'll loose the referrer info so I don't really suggest omitting GA script.

**Comment by velkony** [comment]
due to the new law I have not right to send cookies to the user if he does not want.
I would like if he accepts the cookies that the site does not be reloaded and GA to be initialized.

**Comment by velkony** [comment]
I think I found what I need
https://github.com/Jyxon/GDPR-Cookie-Compliance/blob/master/README.md
I have to rewrite it for Symfony 4
